# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 142f33c90fb57090f8d965664581aa26845a9077e7936c2eb2d4b85fedb5e46f7da182cef8f1f0e1cce54a2c772e7a8bf60a61d849f5d498aaf3377c6b45346e

test:
  secret_key_base: 3216e220dfc41fb44c85cc0b93f3b6ce47939e162bdf24cfb6f5a23bedf33834fbee3a375cbe48968d4e125344156e0e9ee2ea7e22f4a597f993f98bf399b91d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
